apiVersion: apps/v1
kind: Deployment
metadata:
  name: citas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citas
  template:
    metadata:
      labels:
        app: citas
    spec:
      containers:
      - name: citas-api
        image: citas-api:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: citas-service
spec:
  type: NodePort
  selector:
    app: citas
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080